# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-github-metadata
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jemoji

repository: "daviddarnes/daviddarnes.github.io"

jekyll-mentions: https://twitter.com

# SCSS
sass:
  style: :compressed
  
# Site info
url: http://daviddarnes.github.io
title: "Dave's Open Source Stuff"
description: "Experiments, tools and other projects"
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"

twitter:
  username: daviddarnes

author:
  twitter: daviddarnes
  
seo:
  author: "David Darnes"

